### ISSUE TITLE
General Use Bloater

### ISSUE THREAD

**Issue by saucesteals** [sleeyax/asarmor#12]
The bloat and trashify protections provided are I think a little too similar and weird in how they function 

- One will let u provide gigabytes, won't actually use that to determine the size of the files, randomizes everything else as well
- Other will weirdly determine how many files to put and what their names should be along with the sizes

I myself wasn't quite sure exactly what the two were doing and would rather be a little more confident in the outcome of the protections

Wouldn't it be better to just combine them into one and make it more configurable 
Example:
```ts
config: {
    // Filename
    // Example:
    // () => [".env", "file", "file2"][random(0, 2)] 
    // () => crypto.randomBytes(12).toString("hex")
    filename: () => string
    
    // Amount of files
    // Example:
    // 10
    fileCount: number
    
    // Offest of each file
    // Example:
    // 0
    // () => Math.floor(Math.random() * (Math.pow(2, 32) - 1));
    offset: number | () => number
    
    // Size in bytes
    // Example:
    // 1024 ** 3 (gb)
    // () => crypto.randomInt(20, 100) * (1024 ** 2)
    size: number | () => number
}
```

```ts
  apply(archive: IArchive): IArchive {
    const header = archive.header;

    for (let i = 0; i < this.fileCount; i++) {
      const fileName = this.getFileName() // Get from file from file()
      const size = this.getFileSize() // Get size number or size()
      const offset = this.getOffest() // Get offset number or offset()
      
      header.files[fileName] = {
        size,
        offset,
      }
    }
    
    return {
      headerSize: archive.headerSize,
      header,
    }
  }
```

**Comment by sleeyax** [comment]
Both protections are supposed to have fundamentally different results. Bloat's only purpose is to clog up the hard drive of whoever tries to extract the asar file using `asar extract`. E.g. given `100 GB`, it should write roughly 100 GB worth of random bloat to disk upon extraction. The trashify protection on the other hand adds non-existing files with customizable filenames to the archive which should only result in an error upon extraction.

That being said I think you're on to something bigger though. Thinking about it, it doesn't make much sense to still structure this project into 'protections' since there's only like 3 protections in total, which are overlapping and probably never gonna change much either. 

I'm considering a major update to asarmor, getting rid of the 'protections' structure and just applying a config interface like you suggested. For those who don't care about manual configuration we could export some preset configs like `BloatConfig` and `TrashifyConfig` or something like that. Doing this, the CLI would also need an overhaul; protection flags should be removed and replaced with config values instead plus a `--preset <name>` flag for example to combine the preset configs above. 

I need to think about it a bit more and see if I can find some free time to implement these changes :)

**Comment by saucesteals** [comment]
Bringing customization over everything and presets for quick protections would be a massive improvement for asarmor 
I would be more than happy to help out with contributions to the update if that's possible!

**Comment by sleeyax** [comment]
Progress has been made in the [v2.0](https://github.com/sleeyax/asarmor/tree/2.0) branch. This new major version allows deeper customization and replaces the 'protections' concept with 'patches'. In your case you could write a custom patch like this (when v2 is released) to get the desired result you wanted:
```typescript
import * as asarmor from 'asarmor';
import crypto from 'crypto';

type Config = {
  // Filename
  // Example:
  // () => [".env", "file", "file2"][random(0, 2)] 
  // () => crypto.randomBytes(12).toString("hex")
  filename: () => string
  
  // Amount of files
  // Example:
  // 10
  fileCount: number
  
  // Offest of each file
  // Example:
  // 0
  // Math.floor(Math.random() * (Math.pow(2, 32) - 1));
  offset: number
  
  // Size in bytes
  // Example:
  // 1024 ** 3 (gb)
  // crypto.randomInt(20, 100) * (1024 ** 2)
  size: number
}

function createCustomPatch(config: Config) : asarmor.Patch {
  const files: asarmor.FileEntries = {};

  for (let i = 0; i < config.fileCount; i++) {
    files[config.filename()] = {
      offset: config.offset,
      size: config.size
    };
  }

  return {
    header: {
      files
    }
  };
}

(async () => {
  const archive = await asarmor.open('app.asar');

  await archive.createBackup();

  archive.patch(createCustomPatch({
    fileCount: 10,
    filename: () => crypto.randomBytes(12).toString("hex"),
    offset: Math.floor(Math.random() * (Math.pow(2, 32) - 1)),
    size: 1024 ** 3,
  }));

  await archive.write('protected.asar');
})();
```

**Comment by sleeyax** [comment]
Should be good now in `v2.0.0-beta.1`.
