### ISSUE TITLE
Question about encrypt command in CLI

### ISSUE THREAD

**Issue by Naozumi520** [sleeyax/asarmor#47]
How to use encrypt command in CLI? Do I still need to create afterPack.js and beforePack.js as well as the library method?

Btw, I am using electron packager, here is my command: 

`electron-packager . --overwrite --out=dist/win --platform=win32 --arch=x64 --asar --icon=./public/img/favicon.ico && asarmor -a ./dist/win/app-win32-x64/resources/app.asar -o ./dist/win/app-win32-x64/resources/app.asar --encrypt ./src --key ./key.txt`

After packaging the app, I tried to unpack `app.asar` and the folder node-modules disappeared, I didn't find any native files mentioned in readme.md as well. All the code is still there, but it became some unreadable encrypted format (Is this correct behavior?), and the app can't start without logging anything.

I have read the `electron-asar-encrypt-demo` repo, but don't understand how to use it in my application since I am using npm run command to pack the application.

Please forgive my stupidity if I did it wrong or misunderstood it.

<img width="818" alt="螢幕截圖 2022-06-03 下午4 46 14" src="https://user-images.githubusercontent.com/52615455/171821103-457854be-bf88-4989-8910-038996532014.png">

`main.js` after packed.

**Comment by sleeyax** [comment]
Thank you for submitting an issue. Only  `electron-builder` has been thoroughly tested with asarmor this far, so your input and experience with `electron-packager` is valuable.

When using the encyrption module it's important that you encrypt your source/transpiled code into an asar **before** doing anything else. So yes, you will need some kind of 'after pack' hook where you encrypt the asar before delegating it back to your packager for further processing and some 'before pack' step where you copy the native modules to the right locations. The requirement to encrypt existing source/transpiled code is rather a limitation atm, see #42. I recommend you to walk through [README.md#encryption](https://github.com/sleeyax/asarmor#encryption) with `electron-packager`'s docs at hand and try to translate the steps to that packager.

> After packaging the app, I tried to unpack app.asar and the folder node-modules disappeared

I think this is because you basically told asarmor to only just encrypt the contents of `src` into an .asar file. Follow the advice above and try again.

> but it became some unreadable encrypted format

That's the point of encryption :p
