### ISSUE TITLE
Can't use directories in protections

### ISSUE THREAD

**Issue by AsyncVoid** [sleeyax/asarmor#7]
I can't seem to use any sort of directory when using protections such as FileCrash. 

When I input directories such as
`asarmor.applyProtection(new FileCrash(join('build', 'index.js'), -999));`
`asarmor.applyProtection(new FileCrash('build\\index.js', -999));`
It outputs 'Error: build\index.js not found in archive!'

**Comment by sleeyax** [comment]
Filecrash requires the file to actually exist in the archive. If you're using electron-builder or similar, files will be packaged relative to your program's entry point (i.e. the file path that should be set as the `main` field in package.json). In your case you probably don't need to specify the `build` directory anymore, because it's a parent directory for transpiled source files. Try `asarmor.applyProtection(new FileCrash('index.js', -999));` instead.

**Comment by sleeyax** [comment]
On second thought this issue may require some more attention. Although my suggested solution will most likely work for your setup, subdirectories are still not really supported by the `fileCrash` and `trashify` protections. Given the following asar archive header:
```
{
   "files":{
      "abc.txt":{
         "size":0,
         "offset":"0"
      },
      "foo":{
         "files":{
            "bar.txt":{
               "size":0,
               "offset":"0"
            }
         }
      }
   }
}
```
Applying the filecrash protection like `asarmor.applyProtection(new FileCrash('foo/bar.txt', -999));` won't work because it only looks for files at the top level, in a non-recursive way.

Same goes for the trashify protection: `asarmor.applyProtection(new Trashify(['foo/bar.txt'], Trashify.Randomizers.junkExtension()));` will throw an error.

Question is, do I want to add this feature? This doesn't have a real impact on the functionality of asarmor, in a sense that adding subdirectories won't necessarily make it harder to reverse engineer. It's mostly about aesthetics and usability.

**Comment by AsyncVoid** [comment]
Yeah, I'm afraid I tried with and without the build folder but the javascript file certainly is inside the build folder.
Perhaps I could contribute where it splits '/' to directories and the last on is the file?

**Comment by sleeyax** [comment]
Sure, pull requests are always welcome :)

Way I see it the supplied file path should be split by `/[\/\\]/` regex (so it supports both windows `\` and linux `/`, making it more idiot proof) and then iterate over the directories in the asar header until it got the right `{size, offset}` object. 

For the iteration itself you can do it recursively, using a loop or use this [eval-json-path](https://www.npmjs.com/package/eval-json-path) library which I haven't tested at all but looks promising. 

All protections should be able to benefit from the added (sub)directories support, so the logic should be implemented at the core or should at least be sharable across protections. Also when a directory is not found, it should throw an Error.

This is all I had in mind for this feature, feel free to discuss this further.
